import type { Exercise } from '../types';

export const exercises: Exercise[] = [
  {
    id: 'hello-world',
    lessonId: 'first-program',
    title: 'Hello World',
    difficulty: 'Easy',
    description: 'Print exactly "Hello, C++!" followed by newline.',
    prompt: 'Write a program that prints Hello, C++! to standard output.',
    starterCode: `#include <iostream>\nint main() {\n    // Write your code here\n    return 0;\n}\n`,
    sampleInput: '',
    sampleOutput: 'Hello, C++!',
    concepts: ['iostream', 'main'],
    order: 1,
    testCases: [
      { id: 't1', input: '', expectedOutput: 'Hello, C++!', description: 'Exact output' },
    ],
  },
  {
    id: 'variables-intro',
    lessonId: 'variables',
    title: 'Variable Basics',
    difficulty: 'Easy',
    description: 'Create variables and print their sum.',
    prompt: 'Declare two integers a=15 and b=27 and print their sum.',
    starterCode: `#include <iostream>\nint main(){\n    // Declare a and b\n    return 0;\n}\n`,
    sampleInput: '',
    sampleOutput: '42',
    concepts: ['variables'],
    order: 2,
    testCases: [
      { id: 't1', input: '', expectedOutput: '42' },
    ],
  },
  {
    id: 'operators-basic',
    lessonId: 'operators',
    title: 'Operators',
    difficulty: 'Easy',
    description: 'Compute area of rectangle.',
    prompt: 'Read two integers width and height and print area.',
    starterCode: `#include <iostream>\nint main(){\n    int w,h;\n    std::cin>>w>>h;\n    // compute and print\n    return 0;\n}\n`,
    sampleInput: '5 7',
    sampleOutput: '35',
    concepts: ['operators', 'io'],
    order: 3,
    testCases: [
      { id: 't1', input: '5 7', expectedOutput: '35' },
      { id: 't2', input: '3 4', expectedOutput: '12', isHidden: true },
      { id: 't3', input: '10 10', expectedOutput: '100', isHidden: true },
    ],
  },
  {
    id: 'sum-two-numbers',
    lessonId: 'io',
    title: 'Sum of Two Numbers',
    difficulty: 'Easy',
    description: 'Read two integers and print sum.',
    prompt: 'Write a program that takes two integers as input and prints their sum.',
    starterCode: `#include <iostream>\nint main(){\n    // Write your code here\n    return 0;\n}\n`,
    sampleInput: '5 7',
    sampleOutput: '12',
    concepts: ['io', 'operators'],
    order: 4,
    testCases: [
      { id: 't1', input: '5 7', expectedOutput: '12' },
      { id: 't2', input: '0 0', expectedOutput: '0', isHidden: true },
      { id: 't3', input: '-3 10', expectedOutput: '7', isHidden: true },
      { id: 't4', input: '100 200', expectedOutput: '300', isHidden: true },
    ],
    hints: ['Use std::cin to read', 'Use std::cout to print'],
  },
  {
    id: 'even-odd',
    lessonId: 'conditions',
    title: 'Even or Odd',
    difficulty: 'Easy',
    description: 'Determine if number is even or odd.',
    prompt: 'Read an integer and print "even" if even, "odd" otherwise.',
    starterCode: `#include <iostream>\nint main(){\n    int n;\n    std::cin>>n;\n    return 0;\n}\n`,
    sampleInput: '4',
    sampleOutput: 'even',
    concepts: ['conditions', 'modulo'],
    order: 5,
    testCases: [
      { id: 't1', input: '4', expectedOutput: 'even' },
      { id: 't2', input: '7', expectedOutput: 'odd' },
      { id: 't3', input: '0', expectedOutput: 'even', isHidden: true },
      { id: 't4', input: '-3', expectedOutput: 'odd', isHidden: true },
    ],
  },
  {
    id: 'max-three',
    lessonId: 'conditions',
    title: 'Maximum of Three',
    difficulty: 'Easy',
    description: 'Find max of three integers.',
    prompt: 'Read three integers and print the maximum.',
    starterCode: `#include <iostream>\nint main(){\n    int a,b,c;\n    std::cin>>a>>b>>c;\n    return 0;\n}\n`,
    sampleInput: '3 9 2',
    sampleOutput: '9',
    concepts: ['conditions'],
    order: 6,
    testCases: [
      { id: 't1', input: '3 9 2', expectedOutput: '9' },
      { id: 't2', input: '5 5 5', expectedOutput: '5', isHidden: true },
      { id: 't3', input: '-1 -5 -3', expectedOutput: '-1', isHidden: true },
    ],
  },
  {
    id: 'sum-n',
    lessonId: 'loops',
    title: 'Sum 1 to N',
    difficulty: 'Easy',
    description: 'Sum numbers from 1 to N.',
    prompt: 'Read N and print sum of 1..N.',
    starterCode: `#include <iostream>\nint main(){\n    int n;\n    std::cin>>n;\n    return 0;\n}\n`,
    sampleInput: '5',
    sampleOutput: '15',
    concepts: ['loops'],
    order: 7,
    testCases: [
      { id: 't1', input: '5', expectedOutput: '15' },
      { id: 't2', input: '1', expectedOutput: '1', isHidden: true },
      { id: 't3', input: '10', expectedOutput: '55', isHidden: true },
      { id: 't4', input: '100', expectedOutput: '5050', isHidden: true },
    ],
  },
  {
    id: 'factorial',
    lessonId: 'loops',
    title: 'Factorial',
    difficulty: 'Easy',
    description: 'Compute factorial.',
    prompt: 'Read N (0<=N<=10) and print N!. 0! =1.',
    starterCode: `#include <iostream>\nint main(){\n    int n;\n    std::cin>>n;\n    return 0;\n}\n`,
    sampleInput: '5',
    sampleOutput: '120',
    concepts: ['loops'],
    order: 8,
    testCases: [
      { id: 't1', input: '5', expectedOutput: '120' },
      { id: 't2', input: '0', expectedOutput: '1', isHidden: true },
      { id: 't3', input: '3', expectedOutput: '6', isHidden: true },
    ],
  },
  {
    id: 'is-prime',
    lessonId: 'return-values',
    title: 'Prime Check',
    difficulty: 'Medium',
    description: 'Check if number is prime.',
    prompt: 'Read integer N, print "prime" if prime else "not prime". N>=2.',
    starterCode: `#include <iostream>\nbool is_prime(int n){\n    // implement\n    return false;\n}\nint main(){\n    int n;\n    std::cin>>n;\n    std::cout << (is_prime(n) ? "prime" : "not prime");\n    return 0;\n}\n`,
    sampleInput: '7',
    sampleOutput: 'prime',
    concepts: ['functions', 'loops'],
    order: 9,
    testCases: [
      { id: 't1', input: '7', expectedOutput: 'prime' },
      { id: 't2', input: '8', expectedOutput: 'not prime' },
      { id: 't3', input: '2', expectedOutput: 'prime', isHidden: true },
      { id: 't4', input: '9', expectedOutput: 'not prime', isHidden: true },
      { id: 't5', input: '13', expectedOutput: 'prime', isHidden: true },
    ],
  },
  {
    id: 'array-sum',
    lessonId: 'arrays',
    title: 'Array Sum',
    difficulty: 'Easy',
    description: 'Sum array elements.',
    prompt: 'First line N, second line N integers. Print sum.',
    starterCode: `#include <iostream>\n#include <vector>\nint main(){\n    int n;\n    std::cin>>n;\n    return 0;\n}\n`,
    sampleInput: '4\n1 2 3 4',
    sampleOutput: '10',
    concepts: ['arrays', 'vector'],
    order: 10,
    testCases: [
      { id: 't1', input: '4\n1 2 3 4', expectedOutput: '10' },
      { id: 't2', input: '3\n-1 0 1', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    id: 'palindrome',
    lessonId: 'strings',
    title: 'Palindrome',
    difficulty: 'Medium',
    description: 'Check if string is palindrome (case-sensitive).',
    prompt: 'Read a word (no spaces) and print "yes" if palindrome else "no".',
    starterCode: `#include <iostream>\n#include <string>\nint main(){\n    std::string s;\n    std::cin>>s;\n    return 0;\n}\n`,
    sampleInput: 'racecar',
    sampleOutput: 'yes',
    concepts: ['strings'],
    order: 11,
    testCases: [
      { id: 't1', input: 'racecar', expectedOutput: 'yes' },
      { id: 't2', input: 'hello', expectedOutput: 'no' },
      { id: 't3', input: 'a', expectedOutput: 'yes', isHidden: true },
      { id: 't4', input: 'ab', expectedOutput: 'no', isHidden: true },
    ],
  },
  {
    id: 'vector-filter',
    lessonId: 'vector',
    title: 'Filter Evens',
    difficulty: 'Easy',
    description: 'Print only even numbers.',
    prompt: 'Read N then N ints. Print evens space-separated, or "none".',
    starterCode: `#include <iostream>\n#include <vector>\nint main(){\n    int n;\n    std::cin>>n;\n    std::vector<int> v(n);\n    for(int i=0;i<n;++i) std::cin>>v[i];\n    return 0;\n}\n`,
    sampleInput: '5\n1 2 3 4 5',
    sampleOutput: '2 4',
    concepts: ['vector', 'conditions'],
    order: 12,
    testCases: [
      { id: 't1', input: '5\n1 2 3 4 5', expectedOutput: '2 4' },
      { id: 't2', input: '3\n1 3 5', expectedOutput: 'none', isHidden: true },
      { id: 't3', input: '4\n2 4 6 8', expectedOutput: '2 4 6 8', isHidden: true },
    ],
  },
  {
    id: 'word-count',
    lessonId: 'maps',
    title: 'Word Frequency',
    difficulty: 'Medium',
    description: 'Count occurrences of a word.',
    prompt: 'First line N, next N words. Last line query word. Print count.',
    starterCode: `#include <iostream>\n#include <string>\n#include <unordered_map>\nint main(){\n    int n;\n    std::cin>>n;\n    return 0;\n}\n`,
    sampleInput: '4\napple banana apple orange\napple',
    sampleOutput: '2',
    concepts: ['maps'],
    order: 13,
    testCases: [
      { id: 't1', input: '4\napple banana apple orange\napple', expectedOutput: '2' },
      { id: 't2', input: '3\ncat dog cat\ndog', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    id: 'reverse-string',
    title: 'Reverse String',
    difficulty: 'Easy',
    description: 'Reverse a string.',
    prompt: 'Read a line (may contain spaces) and print reversed.',
    starterCode: `#include <iostream>\n#include <string>\n#include <algorithm>\nint main(){\n    std::string s;\n    std::getline(std::cin,s);\n    return 0;\n}\n`,
    sampleInput: 'hello world',
    sampleOutput: 'dlrow olleh',
    concepts: ['strings', 'algorithms'],
    order: 14,
    testCases: [
      { id: 't1', input: 'hello world', expectedOutput: 'dlrow olleh' },
      { id: 't2', input: 'abc', expectedOutput: 'cba', isHidden: true },
    ],
  },
  {
    id: 'fizzbuzz',
    title: 'FizzBuzz',
    difficulty: 'Easy',
    description: 'Classic FizzBuzz.',
    prompt: 'Read N, for i=1..N print: FizzBuzz if divisible by 3 and 5, Fizz if 3, Buzz if 5, else i. Each on new line.',
    starterCode: `#include <iostream>\nint main(){\n    int n;\n    std::cin>>n;\n    return 0;\n}\n`,
    sampleInput: '5',
    sampleOutput: '1\n2\nFizz\n4\nBuzz',
    concepts: ['loops', 'conditions'],
    order: 15,
    testCases: [
      { id: 't1', input: '5', expectedOutput: '1\n2\nFizz\n4\nBuzz' },
      { id: 't2', input: '15', expectedOutput: '1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz', isHidden: true },
    ],
  },
  {
    id: 'binary-search',
    title: 'Binary Search',
    difficulty: 'Medium',
    description: 'Implement binary search.',
    prompt: 'Read N, sorted array of N ints, and target X. Print index (0-based) or -1 if not found.',
    starterCode: `#include <iostream>\n#include <vector>\nint main(){\n    int n;\n    std::cin>>n;\n    std::vector<int> v(n);\n    for(int i=0;i<n;++i) std::cin>>v[i];\n    int x;\n    std::cin>>x;\n    return 0;\n}\n`,
    sampleInput: '5\n1 3 5 7 9\n5',
    sampleOutput: '2',
    concepts: ['algorithms', 'vector'],
    order: 16,
    testCases: [
      { id: 't1', input: '5\n1 3 5 7 9\n5', expectedOutput: '2' },
      { id: 't2', input: '5\n1 3 5 7 9\n2', expectedOutput: '-1', isHidden: true },
      { id: 't3', input: '1\n10\n10', expectedOutput: '0', isHidden: true },
    ],
  },
];
