import type { Lesson } from '../types';

export const lessons: Lesson[] = [
  // FOUNDATIONS
  {
    id: 'first-program',
    moduleId: 'foundations',
    title: 'Your First Program',
    description: 'Compile and run a minimal C++ program. Understand main, includes, and output.',
    durationMinutes: 10,
    objectives: ['Explain the structure of a C++ program', 'Use iostream to output text', 'Understand compilation and return codes'],
    order: 1,
    prevLessonId: undefined,
    nextLessonId: 'variables',
    exerciseIds: ['hello-world'],
    theory: [
      { type: 'paragraph', text: 'Every C++ program starts with a function called main. It is the entry point the operating system calls.' },
      { type: 'code', code: `#include <iostream>\n\nint main() {\n    std::cout << "Hello, C++!" << std::endl;\n    return 0;\n}`, caption: 'Minimal program' },
      { type: 'heading', text: 'What happens here?' },
      { type: 'list', items: ['#include <iostream> brings I/O facilities into scope', 'std::cout is the standard output stream', '<< sends data to the stream', 'return 0 signals success to the OS'] },
      { type: 'callout', text: 'std::endl inserts a newline and flushes the stream. Prefer \\n for performance when flushing is not needed.', variant: 'tip' },
      { type: 'paragraph', text: 'C++ is compiled: source → compiler → executable. Errors are caught before the program ever runs.' },
    ],
    examples: [
      { id: 'ex1', title: 'Hello with newline', code: `#include <iostream>\nint main() {\n    std::cout << "Learn C++\\n";\n    std::cout << "Build skills.\\n";\n    return 0;\n}`, explanation: 'Using \\n for line breaks.' },
    ],
    takeaway: 'main returns an int, #include imports library code, and std::cout writes to the terminal.',
  },
  {
    id: 'variables',
    moduleId: 'foundations',
    title: 'Variables',
    description: 'Store and name data. Understand initialization and mutability.',
    durationMinutes: 12,
    objectives: ['Declare and initialize variables', 'Understand assignment vs initialization', 'Use meaningful names'],
    order: 2,
    prevLessonId: 'first-program',
    nextLessonId: 'data-types',
    exerciseIds: ['variables-intro'],
    theory: [
      { type: 'paragraph', text: 'A variable is a named region of storage that holds a value. In C++, every variable has a type known at compile time.' },
      { type: 'code', code: `int age = 20;\ndouble price = 19.99;\nbool is_ready = true;`, caption: 'Initialization' },
      { type: 'heading', text: 'Initialization matters' },
      { type: 'paragraph', text: 'Uninitialized variables contain indeterminate values. Always initialize. C++ offers several syntaxes:' },
      { type: 'code', code: `int a = 5;      // copy init\nint b(5);       // direct init\nint c{5};       // uniform init (preferred)\nint d = {5};`, caption: 'Initialization forms' },
      { type: 'callout', text: 'Prefer braced initialization {}. It prevents narrowing conversions like double → int.', variant: 'info' },
    ],
    examples: [
      { id: 'ex1', code: `#include <iostream>\nint main() {\n    int users{128};\n    int active{96};\n    int inactive{users - active};\n    std::cout << inactive << "\\n";\n}`, explanation: 'Variables enable computation.' },
    ],
    takeaway: 'Every variable has a type, a name, and should be initialized before use.',
  },
  {
    id: 'data-types',
    moduleId: 'foundations',
    title: 'Data Types',
    description: 'Built-in types, sizes, and choosing the right representation.',
    durationMinutes: 14,
    objectives: ['List fundamental types', 'Understand type sizes and ranges', 'Use auto appropriately'],
    order: 3,
    prevLessonId: 'variables',
    nextLessonId: 'operators',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'C++ types define size, range, and allowed operations. The fundamentals are integers, floating-point, characters, and bool.' },
      { type: 'code', code: `int count{0};              // typically 32-bit\nlong long big{9'000'000'000}; // at least 64-bit\ndouble ratio{0.75};       // double precision\nchar grade{'A'};          // single character\nbool enabled{false};      // true/false`, caption: 'Fundamental types' },
      { type: 'heading', text: 'Type safety' },
      { type: 'paragraph', text: 'C++ is statically typed. The compiler checks types early, preventing many runtime bugs.' },
      { type: 'callout', text: 'Use digit separators 1\'000\'000 for readability. They are ignored by the compiler.', variant: 'tip' },
    ],
    examples: [
      { id: 'ex1', code: `#include <iostream>\n#include <limits>\nint main(){\n    std::cout << sizeof(int) << " bytes\\n";\n    std::cout << std::numeric_limits<int>::max() << "\\n";\n}`, explanation: 'Inspecting type properties.' },
    ],
    takeaway: 'Choose the smallest type that safely represents your data, and let the compiler enforce correctness.',
  },
  {
    id: 'operators',
    moduleId: 'foundations',
    title: 'Operators',
    description: 'Arithmetic, comparison, logical, and bitwise operators.',
    durationMinutes: 12,
    objectives: ['Use arithmetic and logical operators', 'Understand precedence', 'Avoid common pitfalls with integer division'],
    order: 4,
    prevLessonId: 'data-types',
    nextLessonId: 'io',
    exerciseIds: ['operators-basic'],
    theory: [
      { type: 'paragraph', text: 'Operators are symbols that compute values. C++ follows conventional precedence, but parentheses make intent explicit.' },
      { type: 'code', code: `int a{10}, b{3};\nint sum = a + b;        // 13\nint div = a / b;        // 3, integer division\nint mod = a % b;        // 1\nbool gt = a > b;        // true`, caption: 'Common operators' },
      { type: 'callout', text: 'Integer division truncates toward zero. Cast to double for fractional results: double(a)/b.', variant: 'warning' },
      { type: 'list', items: ['== equality, = assignment — never confuse them', '&& and || short-circuit', '++i vs i++ differ in value and performance'], ordered: false },
    ],
    examples: [
      { id: 'ex1', code: `#include <iostream>\nint main(){\n    int x{7};\n    std::cout << (x % 2 == 0 ? "even" : "odd") << "\\n";\n}`, explanation: 'Ternary and modulo.' },
    ],
    takeaway: 'Operators have precedence; use parentheses for clarity, and remember integer division truncates.',
  },
  {
    id: 'io',
    moduleId: 'foundations',
    title: 'Input and Output',
    description: 'Read from stdin and write formatted output.',
    durationMinutes: 10,
    objectives: ['Read input with cin', 'Format output', 'Handle basic input failures'],
    order: 5,
    prevLessonId: 'operators',
    nextLessonId: 'conditions',
    exerciseIds: ['sum-two-numbers'],
    theory: [
      { type: 'paragraph', text: 'C++ I/O uses streams. std::cin reads from standard input, std::cout writes to standard output.' },
      { type: 'code', code: `#include <iostream>\nint main(){\n    int x, y;\n    std::cout << "Enter two numbers: ";\n    std::cin >> x >> y;\n    std::cout << "Sum: " << x + y << "\\n";\n}`, caption: 'Basic I/O' },
      { type: 'heading', text: 'Checking input' },
      { type: 'paragraph', text: 'Stream extraction returns the stream, which can be tested for failure.' },
      { type: 'code', code: `if(!(std::cin >> x)){\n    std::cerr << "Invalid input\\n";\n    return 1;\n}`, caption: 'Validation' },
    ],
    examples: [
      { id: 'ex1', code: `#include <iostream>\n#include <iomanip>\nint main(){\n    double pi{3.14159};\n    std::cout << std::fixed << std::setprecision(2) << pi << "\\n";\n}`, explanation: 'Formatting with <iomanip>.' },
    ],
    takeaway: 'Streams unify I/O. Always validate input, and use iomanip for precise formatting.',
  },
  {
    id: 'conditions',
    moduleId: 'foundations',
    title: 'Conditions',
    description: 'Branch logic with if, else, and switch.',
    durationMinutes: 13,
    objectives: ['Write if/else chains', 'Use switch correctly', 'Apply boolean logic'],
    order: 6,
    prevLessonId: 'io',
    nextLessonId: 'loops',
    exerciseIds: ['even-odd', 'max-three'],
    theory: [
      { type: 'paragraph', text: 'Programs make decisions. if evaluates a condition; only one branch executes.' },
      { type: 'code', code: `int score{85};\nif(score >= 90){\n    std::cout << "A\\n";\n} else if(score >= 80){\n    std::cout << "B\\n";\n} else {\n    std::cout << "C\\n";\n}`, caption: 'if / else if' },
      { type: 'heading', text: 'switch' },
      { type: 'code', code: `char op{'+'};\nswitch(op){\n    case '+': std::cout << "add\\n"; break;\n    case '-': std::cout << "sub\\n"; break;\n    default:  std::cout << "unknown\\n";\n}`, caption: 'switch statement' },
      { type: 'callout', text: 'Always break in switch unless fall-through is intentional and commented.', variant: 'warning' },
    ],
    examples: [
      { id: 'ex1', code: `bool is_admin{false};\nbool is_owner{true};\nif(is_admin || is_owner){\n    // grant access\n}`, explanation: 'Combining conditions.' },
    ],
    takeaway: 'Use if for ranges, switch for discrete values. Make the common path obvious.',
  },
  {
    id: 'loops',
    moduleId: 'foundations',
    title: 'Loops',
    description: 'Repeat work with for, while, and do-while.',
    durationMinutes: 15,
    objectives: ['Use for loops for counted repetition', 'Use while for condition-based loops', 'Avoid infinite loops'],
    order: 7,
    prevLessonId: 'conditions',
    nextLessonId: 'function-basics',
    exerciseIds: ['sum-n', 'factorial'],
    theory: [
      { type: 'paragraph', text: 'Loops repeat a block while a condition holds. Prefer for when you know the count, while when you don\'t.' },
      { type: 'code', code: `for(int i{0}; i < 5; ++i){\n    std::cout << i << " ";\n}\n\nint n{5};\nwhile(n > 0){\n    std::cout << n-- << "\\n";\n}`, caption: 'Loop forms' },
      { type: 'heading', text: 'Loop safety' },
      { type: 'list', items: ['Initialize loop variables', 'Ensure progress toward termination', 'Prefer ++i over i++ in loops (minor but idiomatic)'] },
    ],
    examples: [
      { id: 'ex1', code: `int sum{0};\nfor(int i{1}; i<=100; ++i) sum += i;`, explanation: 'Accumulation pattern.' },
    ],
    takeaway: 'Loops need initialization, condition, and progress. Get all three right and they never surprise you.',
  },
  // FUNCTIONS
  {
    id: 'function-basics',
    moduleId: 'functions',
    title: 'Function Basics',
    description: 'Define and call functions. Why decomposition matters.',
    durationMinutes: 12,
    objectives: ['Define functions', 'Call functions', 'Understand declaration vs definition'],
    order: 8,
    prevLessonId: 'loops',
    nextLessonId: 'parameters',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'A function is a named unit of work with inputs and an output. It makes code testable and reusable.' },
      { type: 'code', code: `#include <iostream>\n\nint square(int x){\n    return x * x;\n}\n\nint main(){\n    std::cout << square(5) << "\\n"; // 25\n}`, caption: 'Defining a function' },
      { type: 'callout', text: 'Declare functions in headers, define in .cpp files. For this course, we keep everything in one file for clarity.', variant: 'info' },
    ],
    examples: [
      { id: 'ex1', code: `void greet(){\n    std::cout << "Hello\\n";\n}`, explanation: 'void means no return value.' },
    ],
    takeaway: 'Functions turn intent into reusable verbs. Name them clearly.',
  },
  {
    id: 'parameters',
    moduleId: 'functions',
    title: 'Parameters',
    description: 'Pass data by value, reference, and const reference.',
    durationMinutes: 14,
    objectives: ['Pass by value vs reference', 'Use const reference for efficiency', 'Understand parameter lifetimes'],
    order: 9,
    prevLessonId: 'function-basics',
    nextLessonId: 'return-values',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Parameters are how functions receive data. By default C++ passes by value — a copy.' },
      { type: 'code', code: `void by_value(int x){ x = 10; } // caller unchanged\nvoid by_ref(int& x){ x = 10; } // caller changed\nvoid by_const_ref(const std::string& s){ /* read-only, no copy */ }`, caption: 'Parameter passing' },
      { type: 'callout', text: 'For small trivial types (int, double), pass by value. For large types (string, vector), pass by const reference.', variant: 'tip' },
    ],
    examples: [
      { id: 'ex1', code: `void increment(int& n){ ++n; }\nint main(){ int a{5}; increment(a); }`, explanation: 'Modifying through reference.' },
    ],
    takeaway: 'Choose parameter passing deliberately: value for ownership, const& for observation, & for mutation.',
  },
  {
    id: 'return-values',
    moduleId: 'functions',
    title: 'Return Values',
    description: 'Return values, early returns, and error handling patterns.',
    durationMinutes: 12,
    objectives: ['Return values', 'Use early returns', 'Return multiple values via struct/tuple'],
    order: 10,
    prevLessonId: 'parameters',
    nextLessonId: 'scope',
    exerciseIds: ['is-prime'],
    theory: [
      { type: 'paragraph', text: 'return sends a value back to the caller and ends the function.' },
      { type: 'code', code: `bool is_even(int n){\n    return n % 2 == 0;\n}\n\nint max(int a, int b){\n    if(a > b) return a;\n    return b;\n}`, caption: 'Return examples' },
      { type: 'heading', text: 'Multiple values' },
      { type: 'code', code: `#include <tuple>\nstd::tuple<int,int> min_max(int a,int b){\n    return {std::min(a,b), std::max(a,b)};\n}`, caption: 'Returning tuple' },
    ],
    examples: [
      { id: 'ex1', code: `std::optional<int> find_index(...)`, explanation: 'Modern approach for maybe-a-value (C++17).' },
    ],
    takeaway: 'Keep returns simple, use early returns to reduce nesting, and use tuple/struct when you need more than one result.',
  },
  {
    id: 'scope',
    moduleId: 'functions',
    title: 'Scope',
    description: 'Lifetime, block scope, and name lookup.',
    durationMinutes: 10,
    objectives: ['Understand block scope', 'Avoid shadowing', 'Use local variables'],
    order: 11,
    prevLessonId: 'return-values',
    nextLessonId: 'overloading',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Scope is the region where a name is visible. C++ has block scope {} — variables die at the closing brace.' },
      { type: 'code', code: `int main(){\n    int x{1};\n    {\n        int x{2}; // shadows outer x\n        std::cout << x; // 2\n    }\n    std::cout << x; // 1\n}`, caption: 'Shadowing' },
      { type: 'callout', text: 'Shadowing is legal but confusing. Enable -Wshadow and avoid reusing names.', variant: 'warning' },
    ],
    examples: [
      { id: 'ex1', code: `for(int i{0}; i<3; ++i){ /* i only here */ } // i not visible`, explanation: 'For-loop scope.' },
    ],
    takeaway: 'Keep scope as small as possible. Define variables where first used.',
  },
  {
    id: 'overloading',
    moduleId: 'functions',
    title: 'Function Overloading',
    description: 'Same name, different parameters. Let the compiler choose.',
    durationMinutes: 11,
    objectives: ['Overload functions', 'Understand overload resolution', 'Avoid ambiguous overloads'],
    order: 12,
    prevLessonId: 'scope',
    nextLessonId: 'arrays',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Overloading lets you provide multiple functions with the same name but different parameter lists.' },
      { type: 'code', code: `int add(int a,int b){ return a+b; }\ndouble add(double a,double b){ return a+b; }\nstd::string add(const std::string& a,const std::string& b){ return a+b; }`, caption: 'Overloads' },
      { type: 'paragraph', text: 'The compiler picks the best match based on argument types. Return type alone does not distinguish overloads.' },
    ],
    examples: [
      { id: 'ex1', code: `void print(int); void print(std::string);`, explanation: 'Same verb, different data.' },
    ],
    takeaway: 'Overloading expresses one idea for many types. Keep overloads semantically consistent.',
  },
  // DATA STRUCTURES
  {
    id: 'arrays',
    moduleId: 'data-structures',
    title: 'Arrays',
    description: 'Fixed-size contiguous storage and indexing.',
    durationMinutes: 12,
    objectives: ['Use C-style and std::array', 'Understand indexing and bounds', 'Iterate safely'],
    order: 13,
    prevLessonId: 'overloading',
    nextLessonId: 'strings',
    exerciseIds: ['array-sum'],
    theory: [
      { type: 'paragraph', text: 'Arrays store N elements contiguously. Indexing is 0-based.' },
      { type: 'code', code: `int scores[5]{90,85,92,78,88};\nstd::cout << scores[0]; // 90\n// Prefer std::array for safety\n#include <array>\nstd::array<int,5> arr{90,85,92,78,88};\nstd::cout << arr.size();`, caption: 'Arrays' },
      { type: 'callout', text: 'Raw arrays decay to pointers. std::array preserves size and works with STL.', variant: 'tip' },
    ],
    examples: [{ id: 'ex1', code: `for(size_t i{0}; i<arr.size(); ++i) std::cout << arr[i];`, explanation: 'Manual iteration.' }],
    takeaway: 'Prefer std::array over C arrays. Never access out of bounds.',
  },
  {
    id: 'strings',
    moduleId: 'data-structures',
    title: 'Strings',
    description: 'Text handling with std::string.',
    durationMinutes: 13,
    objectives: ['Use std::string', 'Concatenate and search', 'Understand string views'],
    order: 14,
    prevLessonId: 'arrays',
    nextLessonId: 'vector',
    exerciseIds: ['palindrome'],
    theory: [
      { type: 'paragraph', text: 'std::string owns and manages character storage. It grows dynamically.' },
      { type: 'code', code: `#include <string>\nstd::string name{"Ada"};\nname += " Lovelace";\nstd::cout << name.size() << "\\n";\nif(name.find("Love") != std::string::npos){ /* found */ }`, caption: 'String basics' },
      { type: 'callout', text: 'For non-owning read-only views, use std::string_view (C++17) to avoid copies.', variant: 'info' },
    ],
    examples: [{ id: 'ex1', code: `std::string s{"hello"};\nfor(char c: s) std::cout << c;`, explanation: 'Range iteration.' }],
    takeaway: 'std::string is the default for owned text. Use string_view for observation.',
  },
  {
    id: 'vector',
    moduleId: 'data-structures',
    title: 'std::vector',
    description: 'Dynamic array — the workhorse container.',
    durationMinutes: 15,
    objectives: ['Use vector', 'Push, pop, and access', 'Understand capacity vs size'],
    order: 15,
    prevLessonId: 'strings',
    nextLessonId: 'std-array',
    exerciseIds: ['vector-filter'],
    theory: [
      { type: 'paragraph', text: 'vector is a resizable array that manages its own memory. It stores elements contiguously.' },
      { type: 'code', code: `#include <vector>\nstd::vector<int> v{1,2,3};\nv.push_back(4);\nstd::cout << v.size(); // 4\nfor(int x: v) std::cout << x << " ";`, caption: 'Vector usage' },
      { type: 'heading', text: 'Capacity' },
      { type: 'paragraph', text: 'size is number of elements, capacity is allocated storage. push_back may reallocate when size == capacity.' },
      { type: 'code', code: `v.reserve(100); // avoid repeated reallocations`, caption: 'Reserve' },
    ],
    examples: [{ id: 'ex1', code: `std::vector<int> evens;\nfor(int i{0}; i<10; ++i) if(i%2==0) evens.push_back(i);`, explanation: 'Filtering into vector.' }],
    takeaway: 'vector is your default container. Reserve when you know the final size.',
  },
  {
    id: 'std-array',
    moduleId: 'data-structures',
    title: 'std::array',
    description: 'Fixed-size array with value semantics.',
    durationMinutes: 8,
    objectives: ['Use std::array', 'Compare with vector and C arrays'],
    order: 16,
    prevLessonId: 'vector',
    nextLessonId: 'maps',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'std::array<T,N> is a thin wrapper over T[N] with STL interface and no overhead.' },
      { type: 'code', code: `#include <array>\nstd::array<int,3> a{1,2,3};\na[0] = 10;\n// a.size() is compile-time constant`, caption: 'std::array' },
    ],
    examples: [{ id: 'ex1', code: `std::array<int,3> p{1,2,3}; // copyable, assignable`, explanation: 'Value semantics.' }],
    takeaway: 'Use std::array when size is known at compile time and never changes.',
  },
  {
    id: 'maps',
    moduleId: 'data-structures',
    title: 'Maps',
    description: 'Key-value storage with std::map and std::unordered_map.',
    durationMinutes: 14,
    objectives: ['Use map and unordered_map', 'Choose between ordered and hashed', 'Iterate entries'],
    order: 17,
    prevLessonId: 'std-array',
    nextLessonId: 'sets',
    exerciseIds: ['word-count'],
    theory: [
      { type: 'paragraph', text: 'Maps associate keys with values. std::map is ordered (tree), unordered_map is hashed (average O(1)).' },
      { type: 'code', code: `#include <unordered_map>\n#include <string>\nstd::unordered_map<std::string,int> freq;\nfreq["apple"]++;\nfor(auto& [k,v]: freq){\n    std::cout << k << ":" << v << "\\n";\n}`, caption: 'Unordered map' },
      { type: 'callout', text: 'Prefer unordered_map unless you need ordering or deterministic iteration.', variant: 'tip' },
    ],
    examples: [{ id: 'ex1', code: `if(auto it = freq.find("apple"); it != freq.end()) std::cout << it->second;`, explanation: 'Finding safely.' }],
    takeaway: 'Maps model dictionaries. Use unordered_map by default, map when order matters.',
  },
  {
    id: 'sets',
    moduleId: 'data-structures',
    title: 'Sets',
    description: 'Unique collection of keys.',
    durationMinutes: 10,
    objectives: ['Use set and unordered_set', 'Test membership'],
    order: 18,
    prevLessonId: 'maps',
    nextLessonId: 'classes',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Sets store unique values. Useful for membership testing and deduplication.' },
      { type: 'code', code: `#include <unordered_set>\nstd::unordered_set<int> seen;\nseen.insert(5);\nif(seen.contains(5)) std::cout << "yes\\n"; // C++20`, caption: 'Set usage' },
    ],
    examples: [{ id: 'ex1', code: `std::unordered_set<int> s{1,2,2,3}; // {1,2,3}`, explanation: 'Uniqueness.' }],
    takeaway: 'Sets answer "have I seen this?" efficiently.',
  },
  // OOP
  {
    id: 'classes',
    moduleId: 'oop',
    title: 'Classes',
    description: 'Define your own types with data and behavior.',
    durationMinutes: 16,
    objectives: ['Define classes', 'Understand public/private', 'Create member functions'],
    order: 19,
    prevLessonId: 'sets',
    nextLessonId: 'objects',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'A class bundles data and functions that operate on that data. It is a blueprint for objects.' },
      { type: 'code', code: `class BankAccount{\npublic:\n    void deposit(double amount){ balance += amount; }\n    double get_balance() const { return balance; }\nprivate:\n    double balance{0};\n};`, caption: 'Class definition' },
      { type: 'heading', text: 'const member functions' },
      { type: 'paragraph', text: 'Mark methods that do not modify state as const. They can be called on const objects.' },
    ],
    examples: [{ id: 'ex1', code: `BankAccount acc; acc.deposit(100);`, explanation: 'Using a class.' }],
    takeaway: 'Classes encapsulate invariants. Public interface, private data.',
  },
  {
    id: 'objects',
    moduleId: 'oop',
    title: 'Objects',
    description: 'Instantiate and use class instances.',
    durationMinutes: 10,
    objectives: ['Create objects', 'Understand value semantics', 'Use object lifetimes'],
    order: 20,
    prevLessonId: 'classes',
    nextLessonId: 'constructors',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Objects are instances of classes. In C++, objects have value semantics by default — copying copies data.' },
      { type: 'code', code: `BankAccount a;\nBankAccount b = a; // copy\nb.deposit(50); // a unchanged`, caption: 'Value semantics' },
    ],
    examples: [{ id: 'ex1', code: `std::vector<BankAccount> accounts; accounts.emplace_back();`, explanation: 'Objects in containers.' }],
    takeaway: 'C++ objects behave like values. Copying is explicit and meaningful.',
  },
  {
    id: 'constructors',
    moduleId: 'oop',
    title: 'Constructors',
    description: 'Initialize objects correctly.',
    durationMinutes: 14,
    objectives: ['Write constructors', 'Use initializer lists', 'Understand default and copy'],
    order: 21,
    prevLessonId: 'objects',
    nextLessonId: 'encapsulation',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Constructors establish invariants. They run when an object is created.' },
      { type: 'code', code: `class Point{\npublic:\n    Point(double x, double y): x_{x}, y_{y} {}\n    Point(): Point{0,0} {} // delegating\nprivate:\n    double x_{0}, y_{0};\n};`, caption: 'Constructors' },
      { type: 'callout', text: 'Use member initializer lists, not assignment in body. It is more efficient and required for const members.', variant: 'tip' },
    ],
    examples: [{ id: 'ex1', code: `Point p{3,4}; Point origin;`, explanation: 'Construction.' }],
    takeaway: 'Constructors should leave the object in a valid state. Prefer initializer lists.',
  },
  {
    id: 'encapsulation',
    moduleId: 'oop',
    title: 'Encapsulation',
    description: 'Hide implementation, expose intent.',
    durationMinutes: 11,
    objectives: ['Apply encapsulation', 'Use getters/setters judiciously', 'Maintain invariants'],
    order: 22,
    prevLessonId: 'constructors',
    nextLessonId: 'inheritance',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Encapsulation protects invariants by controlling access. Not every field needs a getter/setter.' },
      { type: 'code', code: `class Temperature{\npublic:\n    explicit Temperature(double celsius): c_{celsius} {}\n    double celsius() const { return c_; }\n    double fahrenheit() const { return c_*9/5+32; }\nprivate:\n    double c_;\n};`, caption: 'Encapsulation' },
    ],
    examples: [{ id: 'ex1', code: `// No direct access to c_, only through meaningful operations`, explanation: 'Invariant protection.' }],
    takeaway: 'Encapsulation is about preserving meaning, not just hiding data.',
  },
  {
    id: 'inheritance',
    moduleId: 'oop',
    title: 'Inheritance',
    description: 'Reuse and extend behavior through base classes.',
    durationMinutes: 15,
    objectives: ['Use public inheritance', 'Understand is-a relationships', 'Avoid deep hierarchies'],
    order: 23,
    prevLessonId: 'encapsulation',
    nextLessonId: 'polymorphism',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Inheritance models is-a. A Derived is a Base, with extra or specialized behavior.' },
      { type: 'code', code: `struct Shape{ virtual double area() const = 0; virtual ~Shape()=default; };\nstruct Circle: Shape{\n    double r;\n    explicit Circle(double r): r{r} {}\n    double area() const override { return 3.14159*r*r; }\n};`, caption: 'Inheritance' },
      { type: 'callout', text: 'Prefer composition over inheritance unless there is a true is-a relationship.', variant: 'info' },
    ],
    examples: [{ id: 'ex1', code: `Shape* s = new Circle{5};`, explanation: 'Base pointer to derived.' }],
    takeaway: 'Inheritance is for polymorphism, not just code reuse. Keep hierarchies shallow.',
  },
  {
    id: 'polymorphism',
    moduleId: 'oop',
    title: 'Polymorphism',
    description: 'Virtual functions and dynamic dispatch.',
    durationMinutes: 14,
    objectives: ['Use virtual and override', 'Understand vtables', 'Use abstract classes'],
    order: 24,
    prevLessonId: 'inheritance',
    nextLessonId: 'references',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Polymorphism lets you call derived implementations through a base interface.' },
      { type: 'code', code: `void print_area(const Shape& s){\n    std::cout << s.area() << "\\n"; // dynamic dispatch\n}\nCircle c{5};\nprint_area(c);`, caption: 'Polymorphic call' },
      { type: 'heading', text: 'Rules' },
      { type: 'list', items: ['Base destructor must be virtual', 'Use override to catch mismatches', 'Pure virtual =0 makes class abstract'] },
    ],
    examples: [{ id: 'ex1', code: `struct Drawable{ virtual void draw() const = 0; };`, explanation: 'Interface.' }],
    takeaway: 'Polymorphism separates what from how. Depend on abstractions.',
  },
  // MEMORY
  {
    id: 'references',
    moduleId: 'memory',
    title: 'References',
    description: 'Aliases with safety guarantees.',
    durationMinutes: 12,
    objectives: ['Use lvalue references', 'Understand reference binding', 'Use const references'],
    order: 25,
    prevLessonId: 'polymorphism',
    nextLessonId: 'pointers',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'A reference is an alias — another name for an existing object. It cannot be null and cannot be reseated.' },
      { type: 'code', code: `int x{5};\nint& ref = x;\nref = 10; // x is now 10\n// int& bad; // error: must be initialized`, caption: 'References' },
      { type: 'callout', text: 'References are safer than pointers for aliasing. Use them when null is not a valid state.', variant: 'tip' },
    ],
    examples: [{ id: 'ex1', code: `void print(const std::string& s){ std::cout << s; }`, explanation: 'Const reference parameter.' }],
    takeaway: 'References express aliasing without null. Prefer them over pointers when possible.',
  },
  {
    id: 'pointers',
    moduleId: 'memory',
    title: 'Pointers',
    description: 'Indirection, address-of, and dereference.',
    durationMinutes: 16,
    objectives: ['Use pointers', 'Understand * and &', 'Avoid dangling pointers'],
    order: 26,
    prevLessonId: 'references',
    nextLessonId: 'stack-heap',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'A pointer holds an address. It can be null, can be reseated, and supports arithmetic.' },
      { type: 'code', code: `int x{42};\nint* p = &x; // address-of\nstd::cout << *p; // dereference: 42\n*p = 100; // modify through pointer\np = nullptr; // null`, caption: 'Pointer basics' },
      { type: 'heading', text: 'Dangers' },
      { type: 'list', items: ['Dangling: pointing to destroyed object', 'Null dereference: crash', 'Leak: forgetting to free'] },
    ],
    examples: [{ id: 'ex1', code: `if(p) std::cout << *p;`, explanation: 'Null check.' }],
    takeaway: 'Pointers are powerful but unsafe. In modern C++, use smart pointers or references.',
  },
  {
    id: 'stack-heap',
    moduleId: 'memory',
    title: 'Stack vs Heap',
    description: 'Automatic vs dynamic storage duration.',
    durationMinutes: 12,
    objectives: ['Distinguish stack and heap', 'Understand lifetimes', 'Choose appropriate storage'],
    order: 27,
    prevLessonId: 'pointers',
    nextLessonId: 'dynamic-memory',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Stack objects are automatic — created on scope entry, destroyed on exit. Heap objects live until explicitly freed.' },
      { type: 'code', code: `void func(){\n    int stack_var{5}; // stack, auto freed\n    int* heap_var = new int{5}; // heap, manual\n    delete heap_var; // must free\n}`, caption: 'Stack vs heap' },
      { type: 'callout', text: 'Stack is fast and safe. Prefer it. Use heap only when size or lifetime requires it.', variant: 'info' },
    ],
    examples: [{ id: 'ex1', code: `// vector uses heap internally but looks like stack value`, explanation: 'Abstraction.' }],
    takeaway: 'Default to stack. Heap is for when you truly need dynamic lifetime or large size.',
  },
  {
    id: 'dynamic-memory',
    moduleId: 'memory',
    title: 'Dynamic Memory',
    description: 'new and delete, and why you should rarely use them directly.',
    durationMinutes: 13,
    objectives: ['Use new/delete', 'Understand leaks', 'Appreciate RAII'],
    order: 28,
    prevLessonId: 'stack-heap',
    nextLessonId: 'smart-pointers',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'new allocates on heap, delete frees. Mismatched or missing delete causes leaks or undefined behavior.' },
      { type: 'code', code: `int* p = new int{42};\n// ... use ...\ndelete p;\n// For arrays: new[] / delete[]\nint* arr = new int[10];\ndelete[] arr;`, caption: 'Manual management' },
      { type: 'callout', text: 'Manual new/delete is error-prone. Modern C++ prefers smart pointers and containers.', variant: 'warning' },
    ],
    examples: [{ id: 'ex1', code: `// Leaks if exception occurs before delete`, explanation: 'Exception safety problem.' }],
    takeaway: 'Avoid bare new/delete. They are low-level tools for library authors.',
  },
  {
    id: 'smart-pointers',
    moduleId: 'memory',
    title: 'Smart Pointers',
    description: 'unique_ptr and shared_ptr for safe ownership.',
    durationMinutes: 15,
    objectives: ['Use unique_ptr', 'Use shared_ptr when needed', 'Express ownership'],
    order: 29,
    prevLessonId: 'dynamic-memory',
    nextLessonId: 'raii',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Smart pointers are RAII wrappers that automatically delete heap objects.' },
      { type: 'code', code: `#include <memory>\n{\n    auto ptr = std::make_unique<int>(42);\n    std::cout << *ptr;\n} // automatically deleted\n\n{\n    auto shared = std::make_shared<int>(42);\n    auto copy = shared; // ref count 2\n} // deleted when count reaches 0`, caption: 'Smart pointers' },
      { type: 'heading', text: 'Guidance' },
      { type: 'list', items: ['unique_ptr: sole ownership, zero overhead', 'shared_ptr: shared ownership, has cost', 'weak_ptr: break cycles'] },
    ],
    examples: [{ id: 'ex1', code: `std::unique_ptr<Shape> s = std::make_unique<Circle>(5);`, explanation: 'Polymorphic ownership.' }],
    takeaway: 'unique_ptr is the default smart pointer. Use shared_ptr only when ownership truly shared.',
  },
  {
    id: 'raii',
    moduleId: 'memory',
    title: 'RAII',
    description: 'Resource Acquisition Is Initialization — the core C++ idiom.',
    durationMinutes: 14,
    objectives: ['Understand RAII', 'Write RAII classes', 'Use scope for resource safety'],
    order: 30,
    prevLessonId: 'smart-pointers',
    nextLessonId: 'auto',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'RAII ties resource lifetime to object lifetime. Constructor acquires, destructor releases. Exceptions cannot leak.' },
      { type: 'code', code: `class File{\npublic:\n    File(const char* path){ f = std::fopen(path,"w"); }\n    ~File(){ if(f) std::fclose(f); }\n    File(const File&) = delete;\n    File& operator=(const File&) = delete;\nprivate:\n    std::FILE* f{nullptr};\n};`, caption: 'RAII class' },
      { type: 'callout', text: 'All standard library types follow RAII: vector, string, fstream, lock_guard, unique_ptr.', variant: 'info' },
    ],
    examples: [{ id: 'ex1', code: `{ std::lock_guard<std::mutex> lock{m}; /* critical section */ }`, explanation: 'RAII for locks.' }],
    takeaway: 'RAII is C++\'s answer to resource management. If you manage a resource, wrap it.',
  },
  // MODERN
  {
    id: 'auto',
    moduleId: 'modern',
    title: 'auto',
    description: 'Type deduction for clearer, safer code.',
    durationMinutes: 10,
    objectives: ['Use auto', 'Understand auto& and const auto&', 'Avoid auto pitfalls'],
    order: 31,
    prevLessonId: 'raii',
    nextLessonId: 'range-loops',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'auto deduces the type from the initializer. It reduces repetition and prevents narrowing.' },
      { type: 'code', code: `auto x = 5; // int\nauto y = 3.14; // double\nauto s = std::string{"hello"};\nconst auto& ref = s; // const reference, no copy`, caption: 'auto' },
      { type: 'callout', text: 'Use auto& to observe, const auto& for read-only, auto for owning copies.', variant: 'tip' },
    ],
    examples: [{ id: 'ex1', code: `auto it = vec.begin(); // not std::vector<int>::iterator`, explanation: 'Avoid verbose types.' }],
    takeaway: 'auto makes code more maintainable. Use it, but be explicit when the type is not obvious from context.',
  },
  {
    id: 'range-loops',
    moduleId: 'modern',
    title: 'Range-based Loops',
    description: 'Iterate cleanly over any range.',
    durationMinutes: 9,
    objectives: ['Use range-for', 'Choose reference vs value', 'Avoid invalidation'],
    order: 32,
    prevLessonId: 'auto',
    nextLessonId: 'lambdas',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Range-for is the modern way to iterate. No indices, no off-by-one.' },
      { type: 'code', code: `std::vector<int> v{1,2,3};\nfor(auto x: v) std::cout << x; // copies\nfor(auto& x: v) x *= 2; // modifies\nfor(const auto& x: v) std::cout << x; // observes`, caption: 'Range loops' },
    ],
    examples: [{ id: 'ex1', code: `for(const auto& [key,val] : map) {}`, explanation: 'Structured bindings in loops.' }],
    takeaway: 'Prefer range-for over manual indexing. Choose auto&, const auto&, or auto based on intent.',
  },
  {
    id: 'lambdas',
    moduleId: 'modern',
    title: 'Lambdas',
    description: 'Anonymous functions and closures.',
    durationMinutes: 15,
    objectives: ['Write lambdas', 'Capture variables', 'Use lambdas with algorithms'],
    order: 33,
    prevLessonId: 'range-loops',
    nextLessonId: 'stl-algorithms',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Lambdas are inline callable objects. They can capture variables from surrounding scope.' },
      { type: 'code', code: `auto add = [](int a,int b){ return a+b; };\nint factor{2};\nauto multiply = [factor](int x){ return x*factor; }; // capture by value\nauto inc = [&factor](int x){ factor++; return x*factor; }; // by reference`, caption: 'Lambda syntax' },
      { type: 'callout', text: 'Capture by reference [&] is powerful but dangerous if lambda outlives captured variable.', variant: 'warning' },
    ],
    examples: [{ id: 'ex1', code: `std::sort(v.begin(), v.end(), [](auto a, auto b){ return a>b; });`, explanation: 'Custom comparator.' }],
    takeaway: 'Lambdas make algorithms expressive. Capture minimally and explicitly.',
  },
  {
    id: 'stl-algorithms',
    moduleId: 'modern',
    title: 'STL Algorithms',
    description: 'Transform, filter, and aggregate without raw loops.',
    durationMinutes: 16,
    objectives: ['Use transform, filter, sort', 'Understand iterators', 'Write declarative code'],
    order: 34,
    prevLessonId: 'lambdas',
    nextLessonId: 'templates',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'The STL provides 100+ algorithms that work on iterators. They are efficient, tested, and expressive.' },
      { type: 'code', code: `#include <algorithm>\n#include <vector>\nstd::vector<int> v{1,2,3,4};\nstd::vector<int> out;\nstd::copy_if(v.begin(), v.end(), std::back_inserter(out), [](int x){ return x%2==0; });\nstd::transform(v.begin(), v.end(), v.begin(), [](int x){ return x*x; });`, caption: 'Algorithms' },
      { type: 'callout', text: 'Prefer algorithms over hand-written loops. They communicate intent and reduce bugs.', variant: 'tip' },
    ],
    examples: [{ id: 'ex1', code: `auto it = std::find(v.begin(), v.end(), 3);`, explanation: 'Searching.' }],
    takeaway: 'Algorithms separate what from how. Learn them and your code becomes clearer.',
  },
  {
    id: 'templates',
    moduleId: 'modern',
    title: 'Templates',
    description: 'Generic code that works for any type.',
    durationMinutes: 18,
    objectives: ['Write function templates', 'Understand instantiation', 'Use concepts (C++20)'],
    order: 35,
    prevLessonId: 'stl-algorithms',
    nextLessonId: 'move-semantics',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Templates let you write code once for many types. The compiler generates specific versions as needed.' },
      { type: 'code', code: `template<typename T>\nT max_val(T a, T b){\n    return a > b ? a : b;\n}\nauto m1 = max_val(3,5); // int\n\nauto m2 = max_val(3.2, 2.1); // double`, caption: 'Function template' },
      { type: 'heading', text: 'Concepts (C++20)' },
      { type: 'code', code: `template<std::totally_ordered T>\nT max_val(T a, T b){ return a>b?a:b; }`, caption: 'Constrained template' },
    ],
    examples: [{ id: 'ex1', code: `template<typename T> class Vec { /* ... */ };`, explanation: 'Class templates.' }],
    takeaway: 'Templates enable zero-cost abstraction. Constrain them with concepts for better errors.',
  },
  {
    id: 'move-semantics',
    moduleId: 'modern',
    title: 'Move Semantics',
    description: 'Transfer ownership efficiently without copying.',
    durationMinutes: 16,
    objectives: ['Understand lvalues vs rvalues', 'Use std::move', 'Write move-aware types'],
    order: 36,
    prevLessonId: 'templates',
    nextLessonId: 'constexpr',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'Copying can be expensive. Moving transfers resources, leaving source in valid but unspecified state.' },
      { type: 'code', code: `std::string s1{"hello"};\nstd::string s2 = std::move(s1); // s1 now empty-ish, s2 owns data\n\nvoid take(std::string s); // by value, can move into\ntake(std::move(s2));`, caption: 'Move' },
      { type: 'callout', text: 'std::move is just a cast to rvalue reference. It does not move by itself — the move constructor does.', variant: 'info' },
    ],
    examples: [{ id: 'ex1', code: `std::vector<std::string> v; v.push_back(std::string{"temp"}); // may move`, explanation: 'Implicit moves.' }],
    takeaway: 'Move semantics make value types efficient. Use std::move to transfer ownership explicitly.',
  },
  {
    id: 'constexpr',
    moduleId: 'modern',
    title: 'constexpr',
    description: 'Compute at compile time.',
    durationMinutes: 12,
    objectives: ['Use constexpr', 'Understand compile-time evaluation', 'Write consteval functions'],
    order: 37,
    prevLessonId: 'move-semantics',
    nextLessonId: 'error-handling',
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'constexpr tells the compiler a value or function can be evaluated at compile time.' },
      { type: 'code', code: `constexpr int square(int x){ return x*x; }\nconstexpr int v = square(5); // computed at compile time\nstatic_assert(square(3)==9);`, caption: 'constexpr' },
      { type: 'callout', text: 'C++20 allows many STL operations in constexpr, including vector and string.', variant: 'tip' },
    ],
    examples: [{ id: 'ex1', code: `consteval int compile_only(int x){ return x; }`, explanation: 'Must be compile-time.' }],
    takeaway: 'constexpr moves work to compile time, catching errors earlier and improving runtime.',
  },
  {
    id: 'error-handling',
    moduleId: 'modern',
    title: 'Modern Error Handling',
    description: 'Exceptions, optional, expected, and error codes.',
    durationMinutes: 15,
    objectives: ['Use exceptions appropriately', 'Use std::optional and std::expected', 'Choose error strategy'],
    order: 38,
    prevLessonId: 'constexpr',
    nextLessonId: undefined,
    exerciseIds: [],
    theory: [
      { type: 'paragraph', text: 'C++ offers multiple error handling strategies. Choose based on whether failure is exceptional.' },
      { type: 'code', code: `#include <optional>\n#include <stdexcept>\nstd::optional<int> parse_int(const std::string& s){\n    try{ return std::stoi(s); }\n    catch(...){ return std::nullopt; }\n}\n\nint must_parse(const std::string& s){\n    if(s.empty()) throw std::invalid_argument{"empty"};\n    return std::stoi(s);\n}`, caption: 'Error handling' },
      { type: 'heading', text: 'Guidance' },
      { type: 'list', items: ['Use optional for maybe-a-value', 'Use expected (C++23) for value-or-error', 'Use exceptions for truly exceptional, non-local failures', 'Use error codes in performance-critical or no-exception contexts'] },
    ],
    examples: [{ id: 'ex1', code: `if(auto v = parse_int(s)) use(*v);`, explanation: 'Handling optional.' }],
    takeaway: 'No single error strategy fits all. Match the mechanism to the failure mode.',
  },
];
