import type { Module } from '../types';

export const modules: Module[] = [
  {
    id: 'foundations',
    title: 'C++ Foundations',
    description: 'Core syntax, types, control flow, and I/O. The ground floor of every C++ program.',
    order: 1,
    lessonIds: [
      'first-program',
      'variables',
      'data-types',
      'operators',
      'io',
      'conditions',
      'loops',
    ],
  },
  {
    id: 'functions',
    title: 'Functions',
    description: 'Decompose problems, manage scope, and build reusable logic.',
    order: 2,
    lessonIds: [
      'function-basics',
      'parameters',
      'return-values',
      'scope',
      'overloading',
    ],
  },
  {
    id: 'data-structures',
    title: 'Core Data Structures',
    description: 'Arrays, strings, vectors, and associative containers from the standard library.',
    order: 3,
    lessonIds: [
      'arrays',
      'strings',
      'vector',
      'std-array',
      'maps',
      'sets',
    ],
  },
  {
    id: 'oop',
    title: 'Object-Oriented C++',
    description: 'Classes, objects, constructors, and polymorphism — modelling real systems.',
    order: 4,
    lessonIds: [
      'classes',
      'objects',
      'constructors',
      'encapsulation',
      'inheritance',
      'polymorphism',
    ],
  },
  {
    id: 'memory',
    title: 'Memory and Ownership',
    description: 'References, pointers, stack vs heap, and modern ownership.',
    order: 5,
    lessonIds: [
      'references',
      'pointers',
      'stack-heap',
      'dynamic-memory',
      'smart-pointers',
      'raii',
    ],
  },
  {
    id: 'modern',
    title: 'Modern C++',
    description: 'C++17/20 idioms: auto, lambdas, algorithms, templates, move semantics.',
    order: 6,
    lessonIds: [
      'auto',
      'range-loops',
      'lambdas',
      'stl-algorithms',
      'templates',
      'move-semantics',
      'constexpr',
      'error-handling',
    ],
  },
];
