import type { Project } from '../types';

export const projects: Project[] = [
  {
    id: 'cli-calculator',
    title: 'CLI Calculator',
    description: 'A command-line calculator supporting +, -, *, / and parentheses.',
    difficulty: 'Beginner',
    estimatedHours: 3,
    goal: 'Build a calculator that parses and evaluates arithmetic expressions from stdin.',
    requirements: [
      'Read expressions like "3 + 4 * (2 - 1)" from stdin',
      'Support +, -, *, /, parentheses, and floating point numbers',
      'Handle division by zero gracefully',
      'Print result or error message',
      'Loop until user types "exit"',
    ],
    milestones: [
      { title: 'Basic operations', description: 'Implement +, -, *, / for two numbers' },
      { title: 'Expression parsing', description: 'Handle operator precedence and parentheses' },
      { title: 'Error handling', description: 'Detect invalid input and division by zero' },
      { title: 'REPL loop', description: 'Add interactive loop with exit command' },
    ],
    concepts: ['parsing', 'stack', 'error handling', 'loops'],
    hints: ['Use shunting-yard algorithm', 'Consider std::stack for evaluation', 'Test edge cases early'],
  },
  {
    id: 'guessing-game',
    title: 'Number Guessing Game',
    description: 'Interactive game where player guesses a random number.',
    difficulty: 'Beginner',
    estimatedHours: 2,
    goal: 'Create a game that generates a random number and gives hints until guessed.',
    requirements: [
      'Generate random number 1-100',
      'Read user guesses',
      'Print "too high", "too low", or "correct"',
      'Count attempts',
      'Allow replay',
    ],
    milestones: [
      { title: 'Random generation', description: 'Use <random> to generate number' },
      { title: 'Game loop', description: 'Implement guessing loop with hints' },
      { title: 'Polish', description: 'Add attempt counter and replay option' },
    ],
    concepts: ['random', 'loops', 'conditions', 'io'],
    starterCode: `#include <iostream>\n#include <random>\nint main(){\n    std::mt19937 rng{std::random_device{}()};\n    std::uniform_int_distribution<int> dist{1,100};\n    int secret = dist(rng);\n    // ...\n}\n`,
  },
  {
    id: 'contact-manager',
    title: 'Simple Contact Manager',
    description: 'Manage contacts with add, search, and delete operations.',
    difficulty: 'Intermediate',
    estimatedHours: 4,
    goal: 'Build a contact manager using classes and file I/O.',
    requirements: [
      'Define Contact class with name, phone, email',
      'Store contacts in vector or map',
      'Support add, list, search, delete',
      'Save to file and load on startup',
      'Validate phone/email format',
    ],
    milestones: [
      { title: 'Data model', description: 'Design Contact class and storage' },
      { title: 'CRUD operations', description: 'Implement add, search, delete, list' },
      { title: 'Persistence', description: 'Save/load from file using fstream' },
      { title: 'Validation', description: 'Add input validation' },
    ],
    concepts: ['classes', 'vector', 'file I/O', 'encapsulation'],
  },
  {
    id: 'text-stats',
    title: 'Text Statistics Tool',
    description: 'Analyze text files and report statistics.',
    difficulty: 'Intermediate',
    estimatedHours: 3,
    goal: 'Build a tool that reads text and reports word count, frequency, and readability.',
    requirements: [
      'Read text from file or stdin',
      'Count characters, words, lines',
      'Find most frequent words',
      'Calculate average word length',
      'Handle large files efficiently',
    ],
    milestones: [
      { title: 'Basic counts', description: 'Implement char, word, line counting' },
      { title: 'Frequency analysis', description: 'Use unordered_map for word frequency' },
      { title: 'Advanced stats', description: 'Average length, longest word, etc.' },
      { title: 'File support', description: 'Add file reading capability' },
    ],
    concepts: ['strings', 'maps', 'file I/O', 'algorithms'],
  },
];
